[workspace]
default-members = ["voxrs"]
members = [
  "voxrs",
  "voxrs_ed",
  "voxrs_math",
  "voxrs_types",
  "voxrs_derive",
  "voxrs_asset",
  "voxrs_render",
  "voxrs_core",
  "voxrs_rhi",
]
resolver = "2"

[profile.release]
debug = true
